[package]
name = "purrgres"
version = "1.0.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
tokio = { version = "1.41.1", features = ["full"] }
